defaults: &defaults
  nirror:
    api_base_url: https://api.nirror.com
    static_base_url: https://static.nirror.com
    name: OrganizationName,
    idp: https://jwt-idp.mydomain.com
    apikey: 
    owner: 
    client_id: 
    publickey: |
        -----BEGIN RSA PUBLIC KEY-----
        -----END RSA PUBLIC KEY-----
    pivatekey: |
        -----BEGIN RSA PRIVATE KEY-----
        -----END RSA PRIVATE KEY-----
    
development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults